### ISSUE TITLE
Suggestion: RAML

### ISSUE THREAD

**Issue by willis7** [met-office-lab/restful-weather#1]
Have you considered modeling the REST interface using a tool such as [RAML](http://raml.org/)?

**Comment by AlexHilson** [comment]
Thanks for the suggestion, I think that's a great way to start the conversation before we get too stuck into the implementation.

That said, I feel like the static nature of RAML does conflict a bit with the dynamic nature of HAL style hypermedia controls.

**Comment by willis7** [comment]
Yes, I agree. 

I think that once the project has been through a few development cycles you will want the docs generated from the code.
